---
title: "Maintaining quality diagnosis with digital pathology: a practical guide to ISO 15189 accreditation"
author: Williams BJ, Knowles C, Treanor D
format: revealjs
editor: visual
---

# Maintaining quality diagnosis with digital pathology: a practical guide to ISO 15189 accreditation

Journal of Clinical Pathology 2019;72:663-668.

<http://orcid.org/0000-0002-6641-5503> <https://jcp.bmj.com/content/72/10/663>

## Leeds Teaching Hospitals NHS Trust

-   Eylül 2018'den beri %100 dijital
-   38 konsültan patolog primer tanı için eğitim almış
-   validasyon ile
-   yıllık 80.000 vaka 290.000 preparat
-   günlük 1000 preparat
-   günlük 1 TB veri

## Makale içeriği

-   Tecrübe aktarımı

-   Dökümanlar

-   Laboratuvar açısından

-   Patologlar açısından

-   Risk değerlendirilmesi

-   SOP (standart uygulamalar ve dökümanları)

-   Validasyon ve eğitim

-   Kalibrasyon

-   Kalite kontrol

-   Denetim için gerekli kontrol listelerini hazırlamak

## ISO 15189 Medical laboratories---Requirements for quality and competence

-   Dijital patolojinin klinik histopatolojik tanıya entegrasyonu normal laboratuvar prosedürlerinin değişmesine neden olur.
-   Akreditasyon içinde şunlar yer alır:
    -   donanımların incelenmesi
    -   yazılımların incelenmesi
    -   kalibrasyon
    -   laboratuvar personelinin eğitim ve yeterliliği
    -   patologların eğitim ve yeterliliği

## Genel Prensipler 1

-   İlk değerlendirme
    -   Dökümanların değerlendirilmesi
    -   Çalışan ve yöneticiler ile görüşme
    -   günlük aktivitelerin gözlenmesi
    -   taramanın gözlenmesi
    -   dijital tanının gözlenmesi

## Genel Prensipler 2

-   Süreç stresli, gergin olabilir
-   Dijital patoloji yeni bir basamak olduğundna nasıl denetleneceğinin belirsizliği var
-   Laboratuvar ve patologlardan akreditasyon süreci için kilit kişiler belirlenmeli [^1]
-   Planlama ve hazırlıkların takibi önemli

[^1]: Neden Türkçede kilit kişi de İngilizcede key person??

# Laboratuvarın Hazırlanması

Denetimde şu noktaların dökümanları ve delilleri hazır olmalı

1.  Değişikliklerin Kontrolü

2.  Risk Değerlendirmesi

3.  Doğrulama ve Kabul

4.  Karşılaştırılablirlik ve Tekrarlanabilirlik

5.  Eğitim ve Yeterlilik

6.  Ölçümlerdeki Belirsizlik

## Değişikliklerin Kontrolü

-   Laboratuvar işleyişindeki tüm değişikliklerin yönetimi
-   Tüm değişiklikler kaydedilmeli
-   Gereksiz değişikliklerden kaçınılmalı
-   Olanaklar etkin kullanılmalı
-   İşleyen sürece gereksiz yere ilişilmemeli

## Değişim Kontrolü Sırasındaki Anahtar Konular {.scrollable}


| Genel Öneriler  |
|------|
|Değişiklik önerileri yönetimce tartışılmalı ve karara bağlanmalı. Klinik etki de dikkate alınmalı|
| Değişimin öncüsü olarak bir kişi belirlenmeli | 
| Değişim konusunda mutabık olunmalı |
|Değişikliklerin ne zaman rutine geçeceği herkesçe bilinmeli|

|Sağlık ve Güvenlik|
|------|
|Dijital patolojiye geçilmeden önce tüm sağlık ve güvenlik kontrolleri yapılmalı|
|Tarayıcının laboratuvar içindeki konumu belirlenmeli ve uygun şekilde değerlendirilmeli|
|Ekran kullanımın risk değerlendirilmesi kulanıcılar eğitime/validasyona başlamadan yapılmalı|

|Tespit ve Doğrulama|
|------|
|Tarayıcı performansı rutin şartlarda değerlendirilmeli ve firma verileri ile kıyaslanmalı|
|Değerlendirme verilerinin saklanabileceği uygun bir elektronik ortam belirlenmeli|

|Dış kalite kontrol|
|------|
|Kalite yöneticisi yapılacak değişiklikler konusunda bilgilendirilmeli|
|Dış kalite kontrol anlaşma ve şemaları hazırlanmalı|
|Dış kalite yerine iç kalite de kullanılabilir|

|İç kalite kontrol|
|------|
|İç kalite kontrollerinin sıklığı ve niteliği belli olmalı|
|Kalibrasyon için kullanılan preparat ya da yazılımlar belgelenmeli|


|Bilgi İşlem|
|------|
|Yeni bir yazılım alındığında tüm kullanıcıların baştan sona katıldığı deneme testleri yapılmalı|
|Laboratuvar yazılımlarında planlanan değişiklikler dijital patoloji rutine geçmeden tamamlanmalı|

|Prosedürler|
|------|
|Tüm standart uygulamalar yazılı olmalı ve kalite yönetim sisteminden erişilebilir olmalı
|Tüm eğitim ve yeterlilik kayıtları standart uygulamalara göre kaydedilmeli ve kalite yönetim sistemine yüklenmeli|

|Eğitim|
|------|
|Tüm çalışanlar dijital patolojinin laboratuvarda nasıl yer alacağı ve nasıl kullanılacağı konusunda eğitim almalı|
|Yetkili kullanıcılar (admin,super user) belirlenmeli ve bu kişiler sorunlarla ilgilenmek ve çözmek için detaylı eğitime tabi tutulmalı|

|İletişim|
|------|
|Günlük pratikteki değişiklikler tüm laboratuvara duyurulmalı|
|Kullanıcıya olan etkileri, düzenleme süreci ve zamanı konusunda bilgilendirilmeli |


## Risk Değerlendirmesi

Sağlık ve güvenlik açısından değerlendirme yapılmalı:
- Ekipmanlar (tarayıcı, monitör)
- İş akışı
- Ekipmanların laboratuvarda yerleşimi ve personelin aletleri güvenli bir şekilde kullanması
- Ekranların düzgün ayarlandığındna emin olunmalı ^[Ergonomi, ışık ayarı, ekran kullanımı, mouse kullanımı] ^[ayarlamalar tanısal yeterliliği bozmayacak şekilde ve kullanıcı sağlığını bozmayacak şekilde olmalı] ^[Ekran yeterlilik testi, minimum konfigürasyon]


## Doğrulama ve Kabul  {.scrollable}

- Tarayıcı ve yazılımların yeterli şekilde testten geçirildiğinin gösterilmesi
  - amaca yönelik kullanılabilir
  - firmanın belirttiği nitelikleri mevcut


|Donanım|
|------|
|Tarayıcının iç aksamı beklendiği gibi çalışıyor mu?|
|Tarayıcı belirtilen büyüklükte tarama yapabiliyor mu?|
|Renk skalasındaki değerler (RGB) üreticinin önerdiği değer aralıklarında mı?|


|Yazılım|
|------|
|Görüntüler veritabanına doğru bir şekilde aktarılıyor mu?|
|Görüntüler açılıp değerlendirilebiliyor mu?|
|Görüntüleyici ekranı tanı ve kalite açısından yeterli mi?|


## Karşılaştırılablirlik

- Eğer birden fazla tarayıcı kullanılıyorsa bu tarayıcılardan elde edilen görüntüler eş tanısal kalitede midir?
- Bunun tespiti için farklı dokulardan oluşan bir set ile deneme yapılmalıdır.

- Zemin temiz mi?
- Görüntü odaklanmış mı?
- Boyama canlı ve temiz mi?
- Görünütler farklı tarayıcılarda da karşılaştırılabilir kalitede mi?
- Ana tanısal özelliklerin değerlendirilmesi açısından tarayıcılar arasında farklılık var mı?

## Tekrarlanabilirlik

- Dijital patoloji yeni olduğundan laboratuvarlar arası karşılaştırma yapmak zor olabilir.
- Bunun yerine daha önce taranmış ve tanı verilmiş vakalar tekrar taranarak yeniden değerlendirme ve önceki tanı ile karşılaştırma yapılabilir.





## Eğitim ve Yeterlilik

- Tüm dijital patoloji süreçleri, standart uygulamalar kayıt altında olmalı.
- Laboratuvar personeli bu dökümanlara aşina olmalı ve kolayca ulaşabilmeli

Mesela;
- Tarayıcı nasıl kullanılır?
- Görüntü yazılım ve veritabanları nasıl kullanılır?
- Tarayıcı ve iş akışındaki hatalar nasıl giderilir
- Tarayıcı bakımı nasıl yapılır?



## Eğitim ve Yeterlilik 2

- Eğitim dökümanları, kitapçıkları, yeterlilik testleri kayıt altına alınmalı ve periyodik olarka gözden geçirilmeli. 
- Yeni başlayan tüm kullanıcılara kendi başlarına işleri yürütebileceklerinden emin olabilecekleri şekilde bir eğitim verilmeli.
- Yazılım ve donanım güncellemeleri ile bu dökümanlar da güncellenmeli. 








## Ölçümlerdeki Belirsizlik

- Dijital görüntülerde ölçüm yapılıyorsa bunun için kalibre edilmiş prepratlar ile karşılaştırma yapılmalı. ^[Bende bir kalibrasyon preparatı var. Onu tarayıp ölçüm yapacağım]

- Dijital ölçümlerin (cerrahi sınıra uzaklık, Breslow gibi) patologlarsa doğru yapılmasını sağlamak için patologlara, belli bir vaka grubunda, belli periyotlarla, mikroskop ve dijital ölçümler yaptırılmalı. Gözlemciler arası ve gözlemci içi farklılıklar takip edilmelidir.




# Klinik ve Tanı İtibariyle Değerlendirme


## Validasyon ve Eğitim



## Patologları akreditasyona hazırlamak







## Akreditasyon sonrasında izlem




